stages:
- build
- build_containers

build-api:
  image: node:lts
  stage: build
  script:
    - cd api
    - yarn install --frozen-lockfile
    - yarn build
  artifacts:
    paths:
      - api/dist
build-client:
  image: node:lts
  stage: build
  script:
    - cd client
    - rm .npmrc
    - yarn install --frozen-lockfile
    - yarn build
  artifacts:
    paths:
      - client/build
build_container_api:
  image: docker:latest
  stage: build_containers
  needs:
    - build-client
    - build-api
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" registry.legodard.fr
  script:
    - cd api
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=":api"
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":api-$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - docker build --pull -t "$CI_REGISTRY_IMAGE${tag}" .
    - docker push "$CI_REGISTRY_IMAGE${tag}"
build_container_app:
  image: docker:latest
  stage: build_containers
  needs:
    - build-client
    - build-api
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" registry.legodard.fr
  script:
    - cd client
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=":client"
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":client-$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - docker build --pull -t "$CI_REGISTRY_IMAGE${tag}" .
    - docker push "$CI_REGISTRY_IMAGE${tag}"
