services:
  db:
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
  api:
    build: ./api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB=mongodb://db:27017
    env_file:
      - ./api/.env
    depends_on:
      - db
  client:
    build: ./client
    ports:
      - "4000:3000"
    environment:
      - PORT=3000
    env_file:
      - ./client/.env
volumes:
  mongo_data: