name: Build OCI image
description: Build an OCI image and push it to a registry
inputs:
  working-directory:
    description: 'The working directory to run the build in'
    required: false
    default: '.'
  tag:
    description: 'The tag to apply to the built image'
    required: true
  image:
    description: 'The name of the image to build'
    required: true
  platform:
    description: 'The platform to build the image for'
    required: false
    default: 'linux/amd64'
  gh-repository:
    description: 'The GitHub repository to push the image to'
    required: true
  actor:
    description: 'The GitHub actor to use for logging in'
    required: true
  actor-token:
    description: 'The GitHub actor token to use for logging in'
    required: true
runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ inputs.actor }}
        password: ${{ inputs.actor-token }}
    - name: Build and push
      shell: bash
      run: |
        if [[ "${{ inputs.platform }}" == *"arm64"* ]]; then
          ARCH_SUFFIX="arm64"
        else
          ARCH_SUFFIX="amd64"
        fi
        cd ${{ inputs.working-directory }}
        docker buildx build . --tag ghcr.io/${{ inputs.gh-repository }}/${{ inputs.image }}:${{ inputs.tag }}-${ARCH_SUFFIX} --tag ghcr.io/${{ inputs.gh-repository }}/${{ inputs.image }}:latest-${ARCH_SUFFIX} --platform ${{ inputs.platform }} --push