{{ if .Values.client.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-client
  annotations:
  {{- with .Values.ingress.annotations }}
  {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-client
                port:
                  number: 80
{{ end }}
---
{{ if .Values.api.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-api
  annotations:
  {{- with .Values.ingress.apiAnnotations }}
  {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          {{- if .Values.ingress.apiAnnotations.nginx.ingress.kubernetes.io/rewrite-target }}
          - path: /api(/|$)(.*)
          {{- else }}
          - path: /api
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-api
                port:
                  number: 80
{{ end }}