{{if and .Values.api.authentication.enabled .Values.api.authentication.jwt }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-api-secret
type: Opaque
data:
  jwt.pem: {{ .Values.api.authentication.jwtKey | quote }}
{{end}}
