name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-api:
    name: Build API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        working-directory: ./api
        run: pnpm install --frozen-lockfile
      - name: Build
        working-directory: ./api
        run: pnpm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: api
          path: ./api/dist
  build-client:
    name: Build Client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        working-directory: ./client
        run: ls pnpm-lock.yaml && pnpm install --frozen-lockfile
      - name: Build
        working-directory: ./client
        run: pnpm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: client
          path: ./client/build
