name: Build Docker Image for release
on:
  release:
    types: [created]
  workflow_dispatch: # Allows for manual triggering

jobs:
  client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        working-directory: ./client
        run: pnpm install --frozen-lockfile
      - name: Build
        working-directory: ./client
        run: pnpm run build
      - name: Build and push
        run: |
          docker buildx build . -t ghcr.io/ungarscool1/llama-web/client:${{ github.event.release.tag_name }} -t ghcr.io/ungarscool1/llama-web/client:latest --platform linux/amd64,linux/arm64 --push

  api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        run: |
          docker buildx build . -t ghcr.io/ungarscool1/llama-web/api:${{ github.event.release.tag_name }} -t ghcr.io/ungarscool1/llama-web/api:latest --platform linux/amd64,linux/arm64 --push